name: get_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  sizer: ^2.0.15
  get_storage: ^2.1.1
  fluttertoast: ^8.2.1
  intl: ^0.19.0
  url_launcher: ^6.1.11
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.5
  equatable: ^2.0.5
  flutter_ringtone_player: ^4.0.0+2
  sign_in_with_apple: ^6.1.1
  sqflite: ^2.3.0
  cloud_firestore: ^5.0.1
  connectivity_plus: ^6.0.3
  dio: ^5.1.2
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.4
  image: ^4.0.17
  path_provider: ^2.0.0
  device_info_plus: ^10.1.0
  timezone: ^0.9.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  smooth_page_indicator: ^1.1.0
  scroll_to_hide: ^2.0.1
  lottie: ^3.1.2
  cached_network_image: ^3.3.0
  permission_handler: ^11.1.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^4.0.0

# dependency_overrides:
#   flutter_inappwebview: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/database/
    - assets/images/
    - assets/
    - assets/fonts/
    - assets/animation/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          style: normal
      
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins_Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins_Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins_SemiBold.ttf
          weight: 700

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_Bold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_Medium.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
          weight: 500

    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Thin.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous_Regular.ttf
          weight: 400