// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnraMYiKHlz0WSHDZufdDDS3XQz60uJ-U',
    appId: '1:967148231509:web:32b13d8038fa2030fceddc',
    messagingSenderId: '967148231509',
    projectId: 'flutter-get-template',
    authDomain: 'flutter-get-template.firebaseapp.com',
    storageBucket: 'flutter-get-template.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAghU9_yberlh8iSqpmdKiDS45lXOOpHVY',
    appId: '1:967148231509:android:6ee37c383242bb06fceddc',
    messagingSenderId: '967148231509',
    projectId: 'flutter-get-template',
    storageBucket: 'flutter-get-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklLZ8TSOu8_by7mVFt2Geyf6A8bNO7RI',
    appId: '1:967148231509:ios:8d9ef37eae48e7aefceddc',
    messagingSenderId: '967148231509',
    projectId: 'flutter-get-template',
    storageBucket: 'flutter-get-template.appspot.com',
    iosBundleId: 'com.dev.kit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCklLZ8TSOu8_by7mVFt2Geyf6A8bNO7RI',
    appId: '1:967148231509:ios:74477554730657f3fceddc',
    messagingSenderId: '967148231509',
    projectId: 'flutter-get-template',
    storageBucket: 'flutter-get-template.appspot.com',
    iosBundleId: 'com.example.getTemplate.RunnerTests',
  );
}
